### PR TITLE
Allow output of raw html with display_html=False option of draw

### PR DESCRIPTION
**Pull request by bjonnh**
(default is True to keep compatibility)

### CODE REVIEW

**Comment by patrickfuller** [comment]
I'm not sure I understand the point of this option. Can you please explain?

**Comment by bjonnh** [comment]
I use that to integrate the 3d views in tables or other html tags…

raw_html

**Comment by patrickfuller** [comment]
Makes sense - definitely a useful feature.

There's two minor changes to be made:
 * Replace `if display_html is True:` with just `if display_html:` ([PEP8 ref](https://www.python.org/dev/peps/pep-0008/#programming-recommendations))
 * Add a description of the variable in the function docstring under `Args:`.

I'll merge after that.

**Comment by bjonnh** [comment]
Yups! Corrected.

**Comment by patrickfuller** [comment]
Thanks!

**Pull request merged**
