### PR TITLE
Draw bonds between atoms with unknown element.

### PR DESCRIPTION
**Pull request by ctk3b**
Currently, when an unknown element is present in the file, bonds are not
 drawn to those atoms. 

Also added a function which enables adding new "elements" with customized
visuals, useful when, for example, trying to represent a coarse-grained system.

### CODE REVIEW

**Comment by patrickfuller** [comment]
Looks good to me. Thanks for the pull request.

**Comment by ctk3b** [comment]
Thanks! Could you also add an updated version of `imolecule.min.js` and/or contribute your build scripts for that? I can also add mine instead if your prefer.

**Comment by patrickfuller** [comment]
My 'build' is really lazy. In the `imolecule/js` folder, I run

```
uglifyjs jquery-ui.resizable.js three.min.js TrackballControls.js ShaderToon.js imolecule.js > build/imolecule.min.js
```

I'll do this in the next commit and increment the pypi version.

**Comment by ctk3b** [comment]
This could probably also be done on Travis with every commit.

**Comment by patrickfuller** [comment]
That's much smarter.

**Pull request merged**
